/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Neto
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Logo_01 = new javax.swing.JLabel();
        TituloTelaLogin = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextFieldUsuario = new javax.swing.JTextField();
        lblSENHA = new javax.swing.JLabel();
        lblUSUARIO = new javax.swing.JLabel();
        FUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Padre Arlindo Júnior");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 340, 130, 17);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Organização: ONG Sementes do Bem");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 310, 270, 30);

        Logo_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Logo 01.png"))); // NOI18N
        getContentPane().add(Logo_01);
        Logo_01.setBounds(270, 60, 320, 250);

        TituloTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/TituloTelaLogin.png"))); // NOI18N
        getContentPane().add(TituloTelaLogin);
        TituloTelaLogin.setBounds(30, 0, 550, 60);

        jButtonRegistrar.setText("Registre-se");
        getContentPane().add(jButtonRegistrar);
        jButtonRegistrar.setBounds(160, 270, 90, 23);

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar);
        jButtonEntrar.setBounds(40, 270, 63, 23);

        jPasswordFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(30, 210, 220, 20);

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(30, 140, 220, 20);

        lblSENHA.setText("Senha: ");
        getContentPane().add(lblSENHA);
        lblSENHA.setBounds(30, 190, 40, 20);

        lblUSUARIO.setText("Usuário: ");
        getContentPane().add(lblUSUARIO);
        lblUSUARIO.setBounds(30, 120, 50, 20);

        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Fundo.png"))); // NOI18N
        getContentPane().add(FUNDO);
        FUNDO.setBounds(0, 0, 610, 400);

        setSize(new java.awt.Dimension(610, 419));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
    if (jTextFieldUsuario.getText().equals
("admin")&&jPasswordFieldSenha.getText().equals("admin")){
	TelaPrincipal tela = new TelaPrincipal();
		    tela.setVisible(true);
	dispose();
}
	else{
	       JOptionPane.showMessageDialog(rootPane, "Acesso Negado!");
}     
    
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jPasswordFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaKeyPressed
        if (evt.getKeyCode()!=KeyEvent.VK_ENTER) {
        } else if (jTextFieldUsuario.getText().equals
        ("admin")&&jPasswordFieldSenha.getText().equals("admin")){
            TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible(true);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Acesso Negado!");
        }     
            
    }//GEN-LAST:event_jPasswordFieldSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO;
    private javax.swing.JLabel Logo_01;
    private javax.swing.JLabel TituloTelaLogin;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JLabel lblSENHA;
    private javax.swing.JLabel lblUSUARIO;
    // End of variables declaration//GEN-END:variables
}
